/// Wordlist management for fuzzing.
use std::path::Path;

/// Load a wordlist from a file, one entry per line.
/// Skips empty lines and comments (#).
pub fn load_wordlist(path: &Path) -> std::io::Result<Vec<String>> {
    let content = std::fs::read_to_string(path)?;
    Ok(content
        .lines()
        .map(|l| l.trim().to_string())
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .collect())
}

/// Extended API path wordlist (~200 entries) for fuzzing.
pub fn api_paths() -> Vec<&'static str> {
    vec![
        // Core API paths
        "/api",
        "/api/v1",
        "/api/v2",
        "/api/v3",
        "/api/v4",
        "/rest",
        "/rest/v1",
        "/rest/v2",
        "/graphql",
        "/graphiql",
        "/playground",
        "/swagger.json",
        "/swagger.yaml",
        "/swagger.yml",
        "/openapi.json",
        "/api-docs",
        "/api/swagger",
        "/api/docs",
        "/v1",
        "/v2",
        "/v3",
        // Health & monitoring
        "/health",
        "/healthz",
        "/readyz",
        "/livez",
        "/ping",
        "/pong",
        "/status",
        "/metrics",
        "/info",
        "/version",
        // Auth
        "/login",
        "/logout",
        "/signin",
        "/signup",
        "/register",
        "/auth",
        "/oauth",
        "/oauth2",
        "/token",
        "/refresh",
        "/forgot-password",
        "/reset-password",
        "/change-password",
        // Users
        "/users",
        "/user",
        "/accounts",
        "/account",
        "/profile",
        "/admin",
        "/administrator",
        // Data
        "/search",
        "/query",
        "/filter",
        "/sort",
        "/upload",
        "/download",
        "/export",
        "/import",
        "/backup",
        "/config",
        "/configuration",
        "/settings",
        // WebSocket
        "/ws",
        "/websocket",
        "/socket.io",
        "/events",
        "/realtime",
        // Webhooks
        "/webhook",
        "/webhooks",
        "/callback",
        "/hook",
        "/hooks",
        // Debug
        "/debug",
        "/trace",
        "/log",
        "/logs",
        "/env",
        "/environment",
        "/variables",
        // Files
        "/.env",
        "/.git/config",
        "/.gitignore",
        "/robots.txt",
        "/sitemap.xml",
        "/crossdomain.xml",
        "/clientaccesspolicy.xml",
        // Common framework paths
        "/actuator",
        "/actuator/health",
        ("/actuator/info"),
        "/__admin",
        "/__debug",
        "/__test",
        // API documentation
        "/docs",
        "/documentation",
        "/reference",
        "/rapidoc",
        "/redoc",
        "/swagger",
        "/actuator",
        "/actuator/health",
        // Common file extensions
        "/api.php",
        "/api.jsp",
        "/api.aspx",
        "/index.php",
        "/index.jsp",
        "/index.aspx",
        "/admin.php",
        "/login.php",
        // More discovery
        "/service-worker.js",
        "/manifest.json",
        "/.well-known",
        "/.well-known/security.txt",
        "/.well-known/openid-configuration",
    ]
}

/// Common parameter name wordlist for param fuzzing.
pub fn param_names() -> Vec<&'static str> {
    vec![
        "id",
        "ids",
        "user_id",
        "userId",
        "user-id",
        "token",
        "access_token",
        "refresh_token",
        "api_key",
        "apikey",
        "api-key",
        "key",
        "secret",
        "password",
        "pass",
        "pwd",
        "email",
        "email_address",
        "username",
        "page",
        "page_size",
        "limit",
        "offset",
        "cursor",
        "sort",
        "order",
        "direction",
        "filter",
        "search",
        "q",
        "query",
        "type",
        "format",
        "response_type",
        "callback",
        "redirect",
        "redirect_uri",
        "url",
        "link",
        "href",
        "target",
        "name",
        "title",
        "slug",
        "lang",
        "locale",
        "timezone",
        "debug",
        "verbose",
        "pretty",
        "fields",
        "include",
        "expand",
        "embed",
        "_method",
        "_token",
        "csrf_token",
    ]
}
