//! Built-in wordlist of common API endpoint paths.

/// Extended API path wordlist (~200 entries) for fuzzing.
pub fn api_paths() -> Vec<&'static str> {
    vec![
        // Core API paths
        "/api",
        "/api/v1",
        "/api/v2",
        "/api/v3",
        "/api/v4",
        "/rest",
        "/rest/v1",
        "/rest/v2",
        "/graphql",
        "/graphiql",
        "/playground",
        "/swagger.json",
        "/swagger.yaml",
        "/swagger.yml",
        "/openapi.json",
        "/api-docs",
        "/api/swagger",
        "/api/docs",
        "/v1",
        "/v2",
        "/v3",
        // Health & monitoring
        "/health",
        "/healthz",
        "/readyz",
        "/livez",
        "/ping",
        "/pong",
        "/status",
        "/metrics",
        "/info",
        "/version",
        // Auth
        "/login",
        "/logout",
        "/signin",
        "/signup",
        "/register",
        "/auth",
        "/oauth",
        "/oauth2",
        "/token",
        "/refresh",
        "/forgot-password",
        "/reset-password",
        "/change-password",
        // Users
        "/users",
        "/user",
        "/accounts",
        "/account",
        "/profile",
        "/admin",
        "/administrator",
        // Data
        "/search",
        "/query",
        "/filter",
        "/sort",
        "/upload",
        "/download",
        "/export",
        "/import",
        "/backup",
        "/config",
        "/configuration",
        "/settings",
        // WebSocket
        "/ws",
        "/websocket",
        "/socket.io",
        "/events",
        "/realtime",
        // Webhooks
        "/webhook",
        "/webhooks",
        "/callback",
        "/hook",
        "/hooks",
        // Debug
        "/debug",
        "/trace",
        "/log",
        "/logs",
        "/env",
        "/environment",
        "/variables",
        // Files
        "/.env",
        "/.git/config",
        "/.gitignore",
        "/robots.txt",
        "/sitemap.xml",
        "/crossdomain.xml",
        "/clientaccesspolicy.xml",
        // Common framework paths
        "/actuator",
        "/actuator/health",
        ("/actuator/info"),
        "/__admin",
        "/__debug",
        "/__test",
        // API documentation
        "/docs",
        "/documentation",
        "/reference",
        "/rapidoc",
        "/redoc",
        "/swagger",
        "/actuator",
        "/actuator/health",
        // Common file extensions
        "/api.php",
        "/api.jsp",
        "/api.aspx",
        "/index.php",
        "/index.jsp",
        "/index.aspx",
        "/admin.php",
        "/login.php",
        // More discovery
        "/service-worker.js",
        "/manifest.json",
        "/.well-known",
        "/.well-known/security.txt",
        "/.well-known/openid-configuration",
    ]
}
