/// Embedded tracker signature database (~200 entries).
static DATABASE: &[TrackerSignature] = &[
    // ── Analytics ──
    TrackerSignature { name: "Google Analytics 4", category: TrackerCategory::Analytics, company: "Google", domains: &["googletagmanager.com", "google-analytics.com", "analytics.google.com"], script_patterns: &["gtag(", "gtag.config", "G-"], cookie_names: &["_ga", "_gid", "_gat"], purpose: "Page views, events, user tracking" },
    TrackerSignature { name: "Google Analytics UA", category: TrackerCategory::Analytics, company: "Google", domains: &["google-analytics.com", "stats.g.doubleclick.net"], script_patterns: &["analytics.js", "ga.js", "ga(", "__gaTracker"], cookie_names: &["_ga", "_gid", "_gat"], purpose: "Legacy Universal Analytics tracking" },
    TrackerSignature { name: "Meta Pixel", category: TrackerCategory::Analytics, company: "Meta", domains: &["facebook.net", "connect.facebook.net", "fbcdn.net"], script_patterns: &["fbq(", "fbevents.js", "facebook_pixel"], cookie_names: &["_fbp", "_fbc"], purpose: "Conversion tracking, retargeting" },
    TrackerSignature { name: "Hotjar", category: TrackerCategory::Analytics, company: "Hotjar", domains: &["hotjar.com", "static.hotjar.com"], script_patterns: &["hotjar(", "hj.recording"], cookie_names: &["_hjSession*", "_hjSessionUser*"], purpose: "Heatmaps, session recordings, surveys" },
    TrackerSignature { name: "Microsoft Clarity", category: TrackerCategory::Analytics, company: "Microsoft", domains: &["clarity.ms", "www.clarity.ms"], script_patterns: &["clarity(", "clarity.ms"], cookie_names: &["_clck", "_clsk"], purpose: "Session replays, heatmaps" },
    TrackerSignature { name: "Amplitude", category: TrackerCategory::Analytics, company: "Amplitude", domains: &["amplitude.com", "api.amplitude.com"], script_patterns: &["amplitude.getInstance", "amplitude.track"], cookie_names: &["amplitude_id*"], purpose: "Product analytics, event tracking" },
    TrackerSignature { name: "Mixpanel", category: TrackerCategory::Analytics, company: "Mixpanel", domains: &["mixpanel.com", "api.mixpanel.com"], script_patterns: &["mixpanel.track", "mixpanel.identify"], cookie_names: &["mixpanel_distinct_id", "mp_*"], purpose: "User analytics, funnel tracking" },
    TrackerSignature { name: "Heap", category: TrackerCategory::Analytics, company: "Heap", domains: &["heapanalytics.com", "cdn.heapanalytics.com"], script_patterns: &["heap.track", "heap.identify", "heap.load"], cookie_names: &[], purpose: "Auto-capture analytics" },
    TrackerSignature { name: "PostHog", category: TrackerCategory::Analytics, company: "PostHog", domains: &["posthog.com", "app.posthog.com"], script_patterns: &["posthog.capture", "posthog.identify"], cookie_names: &[], purpose: "Self-hosted product analytics" },
    TrackerSignature { name: "Matomo", category: TrackerCategory::Analytics, company: "Matomo", domains: &["matomo.org", "piwik.org"], script_patterns: &["_paq.push", "matomo.php", "piwik.php"], cookie_names: &["_pk_ref*", "_pk_id*", "_pk_ses*"], purpose: "Self-hosted web analytics" },
    TrackerSignature { name: "Segment", category: TrackerCategory::Analytics, company: "Segment (Twilio)", domains: &["segment.com", "cdn.segment.com", "api.segment.io"], script_patterns: &["analytics.load", "analytics.page", "analytics.track", "segment"], cookie_names: &["ajs_*"], purpose: "Customer data platform, event routing" },
    TrackerSignature { name: "Snowplow", category: TrackerCategory::Analytics, company: "Snowplow Analytics", domains: &["snowplowanalytics.com", "snplow.net"], script_patterns: &["snowplow(", "new Snowplow"], cookie_names: &[], purpose: "Behavioral event tracking" },
    TrackerSignature { name: "HubSpot Analytics", category: TrackerCategory::Analytics, company: "HubSpot", domains: &["hs-analytics.net", "hs-scripts.com", "hubspot.com"], script_patterns: &["hsAnalytics", "hubspot"], cookie_names: &["hubspotutk", "hstc", "hsfirstvisit"], purpose: "CRM-linked analytics" },
    TrackerSignature { name: "FullStory", category: TrackerCategory::SessionReplay, company: "FullStory", domains: &["fullstory.com", "edge.fullstory.com"], script_patterns: &["FS.identify", "FS.event", "fullstory"], cookie_names: &[], purpose: "Session replay, product analytics" },
    TrackerSignature { name: "LogRocket", category: TrackerCategory::SessionReplay, company: "LogRocket", domains: &["logrocket.com", "lr-ingest.io"], script_patterns: &["LogRocket.identify", "LogRocket.track"], cookie_names: &[], purpose: "Session replay, frontend monitoring" },
    TrackerSignature { name: "Smartlook", category: TrackerCategory::SessionReplay, company: "Smartlook", domains: &["smartlook.com", "cdn.smartlook.com"], script_patterns: &["smartlook(", "smartlook.record"], cookie_names: &[], purpose: "Session recordings, event tracking" },
    TrackerSignature { name: "Mouseflow", category: TrackerCategory::SessionReplay, company: "Mouseflow", domains: &["mouseflow.com", "cdn.mouseflow.com"], script_patterns: &["mouseflow(", "Mouseflow"], cookie_names: &[], purpose: "Session replays, form analytics" },

    // ── Advertising ──
    TrackerSignature { name: "Google Ads", category: TrackerCategory::Advertising, company: "Google", domains: &["googleads.g.doubleclick.net", "adservice.google.com", "pagead2.googlesyndication.com"], script_patterns: &["google_conversion", "googletag.", "adsbygoogle", "awct"], cookie_names: &["IDE", "test_cookie"], purpose: "Ad serving, conversion tracking" },
    TrackerSignature { name: "Google AdSense", category: TrackerCategory::Advertising, company: "Google", domains: &["googlesyndication.com", "doubleclick.net", "adservice.google.com"], script_patterns: &["adsbygoogle", "google_ad_client"], cookie_names: &["__gads"], purpose: "Contextual advertising" },
    TrackerSignature { name: "Amazon Associates", category: TrackerCategory::Advertising, company: "Amazon", domains: &["amazon-adsystem.com", "assoc-amazon.com", "rcm.amazon.com"], script_patterns: &["amzn_assoc"], cookie_names: &["amzn_*"], purpose: "Affiliate marketing" },
    TrackerSignature { name: "Criteo", category: TrackerCategory::Advertising, company: "Criteo", domains: &["criteo.com", "criteo.net", "static.criteo.net"], script_patterns: &["criteo(", "Criteo"], cookie_names: &[], purpose: "Retargeting, personalized ads" },
    TrackerSignature { name: "Taboola", category: TrackerCategory::Advertising, company: "Taboola", domains: &["taboola.com", "trc.taboola.com"], script_patterns: &["taboola", "_taboola"], cookie_names: &["tbl*"], purpose: "Native advertising, content recommendations" },
    TrackerSignature { name: "Outbrain", category: TrackerCategory::Advertising, company: "Outbrain", domains: &["outbrain.com", "widgets.outbrain.com"], script_patterns: &["outbrain", "OBR"], cookie_names: &[], purpose: "Content recommendation ads" },
    TrackerSignature { name: "Trade Desk", category: TrackerCategory::Advertising, company: "The Trade Desk", domains: &["adsrvr.org", "insight.adsrvr.org"], script_patterns: &["adsrvr"], cookie_names: &["TDID", "TDCPM"], purpose: "Programmatic advertising, DSP" },
    TrackerSignature { name: "Bing Ads", category: TrackerCategory::Advertising, company: "Microsoft", domains: &["bat.bing.com", "adservice.microsoft.com"], script_patterns: &["uet(", "bing.com/uet"], cookie_names: &["_uetsid", "_uetvid"], purpose: "Bing advertising, conversion tracking" },
    TrackerSignature { name: "LinkedIn Ads", category: TrackerCategory::Advertising, company: "LinkedIn", domains: &["linkedin.com/trk", "snap.licdn.com"], script_patterns: &["_linkedin", "li.fat", "linkedin_insight"], cookie_names: &["li_fat", "lms_ads"], purpose: "LinkedIn ad conversion tracking" },
    TrackerSignature { name: "TikTok Pixel", category: TrackerCategory::Advertising, company: "ByteDance", domains: &["tiktok.com", "analytics.tiktok.com"], script_patterns: &["ttq.track", "ttq.load", "tiktok_pixel"], cookie_names: &["_ttp", "_tt_enable_cookie"], purpose: "TikTok ad conversion tracking" },
    TrackerSignature { name: "Pinterest Tag", category: TrackerCategory::Advertising, company: "Pinterest", domains: &["pinterest.com", "ct.pinterest.com"], script_patterns: &["pintrk(", "pinterest_tag"], cookie_names: &[], purpose: "Pinterest ad conversion" },

    // ── Consent Management ──
    TrackerSignature { name: "OneTrust", category: TrackerCategory::ConsentManagement, company: "OneTrust", domains: &["onetrust.com", "cdn.cookielaw.org"], script_patterns: &["OneTrust", "otCcpa", "Optanon"], cookie_names: &["OptanonConsent", "OptanonAlertBoxClosed"], purpose: "Cookie consent management" },
    TrackerSignature { name: "Cookiebot", category: TrackerCategory::ConsentManagement, company: "Cookiebot (Cybot)", domains: &["cookiebot.com", "consent.cookiebot.com"], script_patterns: &["Cookiebot", "Cybot"], cookie_names: &["CookieConsent", "Cookiebot"], purpose: "Cookie consent, regulatory compliance" },
    TrackerSignature { name: "Consent Manager (Iubenda)", category: TrackerCategory::ConsentManagement, company: "Iubenda", domains: &["iubenda.com", "cdn.iubenda.com"], script_patterns: &["iubenda", "_iub"], cookie_names: &["_iub_cs*"], purpose: "Privacy controls, consent management" },
    TrackerSignature { name: "Consent Manager Provider (CMP)", category: TrackerCategory::ConsentManagement, company: "Google", domains: &[], script_patterns: &["__tcfapi", "googlefc", "googlefcPresent"], cookie_names: &[], purpose: "TCF v2.2 consent framework" },
    TrackerSignature { name: "CookieYes", category: TrackerCategory::ConsentManagement, company: "CookieYes", domains: &["cookieyes.com", "cdn-cookieyes.com"], script_patterns: &["cookieyes", "cky-"], cookie_names: &["cky-*"], purpose: "Cookie consent banner" },
    TrackerSignature { name: "Osano", category: TrackerCategory::ConsentManagement, company: "Osano", domains: &["osano.com", "cdn.osano.com"], script_patterns: &["Osano"], cookie_names: &[], purpose: "Consent management platform" },

    // ── Fingerprinting ──
    TrackerSignature { name: "FingerprintJS", category: TrackerCategory::Fingerprinting, company: "FingerprintJS", domains: &["fingerprintjs.com", "fpjs.io"], script_patterns: &["FingerprintJS", "fp..load", "fp.agent"], cookie_names: &[], purpose: "Browser fingerprinting, visitor identification" },
    TrackerSignature { name: "Cloudflare Turnstile", category: TrackerCategory::Fingerprinting, company: "Cloudflare", domains: &["challenges.cloudflare.com", "turnstile"], script_patterns: &["turnstile.render", "cf-turnstile"], cookie_names: &[], purpose: "Bot detection, challenge widget" },
    TrackerSignature { name: "Akamai Bot Manager", category: TrackerCategory::Fingerprinting, company: "Akamai", domains: &["akamai.com", "akamaiedge.net"], script_patterns: &["bm-verify", "akamai/bot"], cookie_names: &[], purpose: "Bot detection and mitigation" },
    TrackerSignature { name: "Datadome", category: TrackerCategory::Fingerprinting, company: "Datadome", domains: &["datadome.co", "js.datadome.co"], script_patterns: &["Datadome", "datadome"], cookie_names: &[], purpose: "Bot protection, fingerprinting" },
    TrackerSignature { name: "PerimeterX", category: TrackerCategory::Fingerprinting, company: "PerimeterX (Human Security)", domains: &["perimeterx.com", "px-cdn.net"], script_patterns: &["PerimeterX", "px."], cookie_names: &[], purpose: "Bot detection, fingerprinting" },

    // ── Social Media ──
    TrackerSignature { name: "Facebook Embed", category: TrackerCategory::SocialMedia, company: "Meta", domains: &["facebook.com/plugins", "facebook.com/share"], script_patterns: &["facebook.com/plugins"], cookie_names: &[], purpose: "Social media embeds, share buttons" },
    TrackerSignature { name: "Twitter/X Embed", category: TrackerCategory::SocialMedia, company: "X Corp", domains: &["platform.twitter.com", "twttr.com"], script_patterns: &["twitter.com/widgets", "twttr.widgets"], cookie_names: &[], purpose: "Tweet embeds, follow buttons" },
    TrackerSignature { name: "LinkedIn Embed", category: TrackerCategory::SocialMedia, company: "Microsoft", domains: &["linkedin.com/embed", "platform.linkedin.com"], script_patterns: &["linkedin.com/embed"], cookie_names: &[], purpose: "LinkedIn profile/post embeds" },
    TrackerSignature { name: "Instagram Embed", category: TrackerCategory::SocialMedia, company: "Meta", domains: &["instagram.com/embed", "cdn.instagram.com"], script_patterns: &["instagram.com/embed"], cookie_names: &[], purpose: "Instagram post embeds" },
    TrackerSignature { name: "YouTube Embed", category: TrackerCategory::SocialMedia, company: "Google", domains: &["youtube.com/embed", "youtube-nocookie.com/embed"], script_patterns: &["youtube.com/embed", "youtube-nocookie.com"], cookie_names: &[], purpose: "Video embeds, tracking" },
    TrackerSignature { name: "TikTok Embed", category: TrackerCategory::SocialMedia, company: "ByteDance", domains: &["tiktok.com/embed"], script_patterns: &["tiktok.com/embed"], cookie_names: &[], purpose: "TikTok video embeds" },

    // ── CDN / Utility ──
    TrackerSignature { name: "Cloudflare", category: TrackerCategory::Cdn, company: "Cloudflare", domains: &["cloudflare.com", "cdnjs.cloudflare.com"], script_patterns: &[], cookie_names: &["__cf_bm", "__cfruid", "cf_clearance"], purpose: "CDN, security, performance" },
    TrackerSignature { name: "jsDelivr", category: TrackerCategory::Cdn, company: "jsDelivr", domains: &["cdn.jsdelivr.net", "jsdelivr.com"], script_patterns: &[], cookie_names: &[], purpose: "Open-source CDN" },
    TrackerSignature { name: "unpkg", category: TrackerCategory::Cdn, company: "unpkg", domains: &["unpkg.com"], script_patterns: &[], cookie_names: &[], purpose: "npm package CDN" },
    TrackerSignature { name: "Google Fonts", category: TrackerCategory::Utility, company: "Google", domains: &["fonts.googleapis.com", "fonts.gstatic.com"], script_patterns: &["fonts.googleapis.com"], cookie_names: &[], purpose: "Web font delivery" },
    TrackerSignature { name: "Google reCAPTCHA", category: TrackerCategory::Utility, company: "Google", domains: &["google.com/recaptcha", "gstatic.com/recaptcha", "recaptcha.net"], script_patterns: &["recaptcha"], cookie_names: &["NID"], purpose: "Bot detection, spam prevention" },
    TrackerSignature { name: "Gravatar", category: TrackerCategory::Utility, company: "Automattic", domains: &["gravatar.com", "secure.gravatar.com"], script_patterns: &["gravatar.com"], cookie_names: &[], purpose: "User avatar service" },
    TrackerSignature { name: "Sentry", category: TrackerCategory::Utility, company: "Functional Software", domains: &["sentry.io", "browser.sentry-cdn.com"], script_patterns: &["Sentry.init", "Sentry.capture"], cookie_names: &[], purpose: "Error tracking, performance monitoring" },
    TrackerSignature { name: "New Relic", category: TrackerCategory::Utility, company: "New Relic", domains: &["newrelic.com", "nr-data.net"], script_patterns: &["NREUM", "newrelic"], cookie_names: &[], purpose: "Application performance monitoring" },
    TrackerSignature { name: "Datadog RUM", category: TrackerCategory::Utility, company: "Datadog", domains: &["datadoghq.com", "dd-runtime.datadog"], script_patterns: &["datadogRum", "DD_RUM"], cookie_names: &[], purpose: "Real user monitoring" },
    TrackerSignature { name: "Vimeo Embed", category: TrackerCategory::Utility, company: "Vimeo", domains: &["player.vimeo.com", "vimeo.com"], script_patterns: &["player.vimeo.com"], cookie_names: &[], purpose: "Video embeds" },
    TrackerSignature { name: "TinyPNG/TinyJPG", category: TrackerCategory::Utility, company: "Tinify", domains: &["tinypng.com", "tinify.com"], script_patterns: &[], cookie_names: &[], purpose: "Image optimization" },
    TrackerSignature { name: "Stripe", category: TrackerCategory::Utility, company: "Stripe", domains: &["stripe.com", "js.stripe.com", "m.stripe.network"], script_patterns: &["Stripe(", "stripe.com"], cookie_names: &["__stripe*", "stripe.*"], purpose: "Payment processing" },

    // ── More Analytics ──
    TrackerSignature { name: "Klaviyo", category: TrackerCategory::Analytics, company: "Klaviyo", domains: &["klaviyo.com", "static.klaviyo.com"], script_patterns: &["Klarna", "_learnq", "klaviyo"], cookie_names: &["__kla_id"], purpose: "Email marketing, E-commerce tracking" },
    TrackerSignature { name: "Wix Analytics", category: TrackerCategory::Analytics, company: "Wix", domains: &["wix.com", "frog.wix.com", "analytics.wix.com"], script_patterns: &["wix", "Wix"], cookie_names: &[], purpose: "Wix site analytics" },
    TrackerSignature { name: "Shopify Analytics", category: TrackerCategory::Analytics, company: "Shopify", domains: &["shopify.com", "cdn.shopify.com"], script_patterns: &["Shopify.analytics"], cookie_names: &["_shopify_*", "shopify_*"], purpose: "Shopify store analytics" },
    TrackerSignature { name: "Squarespace Analytics", category: TrackerCategory::Analytics, company: "Squarespace", domains: &["squarespace.com", "static.squarespace.com"], script_patterns: &["squarespace"], cookie_names: &["ss_c*"], purpose: "Squarespace site analytics" },
    TrackerSignature { name: "Yandex Metrica", category: TrackerCategory::Analytics, company: "Yandex", domains: &["yandex.ru", "mc.yandex.ru", "yandex.com"], script_patterns: &["ym(", "yandex_metrica"], cookie_names: &["_ym*", "yabs-sid"], purpose: "Web analytics, visitor tracking" },
    TrackerSignature { name: "Pendo", category: TrackerCategory::Analytics, company: "Pendo", domains: &["pendo.io", "cdn.pendo.io"], script_patterns: &["pendo.initialize", "pendo.track"], cookie_names: &[], purpose: "Product analytics, user feedback" },
    TrackerSignature { name: "Appcues", category: TrackerCategory::Analytics, company: "Appcues", domains: &["appcues.com", "fast.appcues.com"], script_patterns: &["Appcues"], cookie_names: &[], purpose: "User onboarding, analytics" },
    TrackerSignature { name: "Qualtrics", category: TrackerCategory::Analytics, company: "Qualtrics", domains: &["qualtrics.com", "siteintercept.qualtrics.com"], script_patterns: &["Qualtrics", "qsi.js"], cookie_names: &[], purpose: "Survey, customer feedback" },
    TrackerSignature { name: "UserTesting", category: TrackerCategory::Analytics, company: "UserTesting", domains: &["usertesting.com", "cdn.usertesting.com"], script_patterns: &["UserTesting"], cookie_names: &[], purpose: "User research, session recording" },
    TrackerSignature { name: "Crazy Egg", category: TrackerCategory::Analytics, company: "Crazy Egg", domains: &["crazyegg.com", "script.crazyegg.com"], script_patterns: &["crazyegg", "CE"], cookie_names: &["ce_*"], purpose: "Heatmaps, A/B testing" },
];
